#!/bin/bash

curl -X POST https://drnull-email-service.pages.dev/generate --header "Content-Type: application/json" -d "context=You are a professional email writer. Your tone is always polite and respectful. You pay attention to detail and ensure that all emails are grammatically correct and well-written, write an email about a subject which the user will provide, do not use placeholders, do not use markdown just provide a template, generate a full professional email.&prompt=Write a professional email to a potential client about accepting their project and wanting to move forward with it"



# separated code from the actul hosted LLM wrapper because I don't currently have the deepseek key
